name: deploy-argocd

trigger: none

variables:
  - group: aws-keys
  - name: AWS_REGION
    value: AATT_AWS_REGION # This value was modified by the initial-setup python script
  - name: APP_NAME
    value: AATT_APP_NAME # This value was modified by the initial-setup python script
    

pool:
  vmImage: 'ubuntu-latest' 
  # If you are using a self-hosted agent, comment out the previous line and uncomment the following three
  # name: <agent-pool-name> # Insert here the name of the agent pool you created
  # demands:
  #   - agent.name -equals <agent-name> # Insert here the name of the agent you created


steps:
- task: HelmInstaller@0
  inputs:
    displayName: Install helm
    helmVersion: '3.11.2'
    installKubectl: true

- task: AWSCLI@1
  displayName: 'Update KubeConfig'
  inputs:
    awsCredentials: 'aws'
    regionName: '$(AWS_REGION)' 
    awsCommand: 'eks'
    awsSubCommand: 'update-kubeconfig'
    awsArguments: '--name $(APP_NAME)-cluster --region $(AWS_REGION)' 

- script: | 
    mkdir ~/.aws
    echo -e "[default]\naws_access_key_id = $(aws_access_key_id)\naws_secret_access_key = $(aws_secret_access_key)" > ~/.aws/credentials
    echo -e "[default]\nregion = $(AWS_REGION)"> ~/.aws/config 
  displayName: 'Configure AWS Profile'

- task: HelmDeploy@0
  displayName: Deploy ArgoCD
  inputs:
    connectionType: 'None'
    namespace: 'argocd'
    chartVersion: '5.34.1'
    command: 'install'
    chartType: 'FilePath'
    chartPath: 'helm/argo-cd'
    valueFile: 'helm/argo-cd/values-custom.yaml'
    arguments: '--dependency-update --create-namespace'

- script: |
    echo "false" > is-active.txt
    while [ "$(cat is-active.txt)" != "true" ]; do
        sleep 5
        aws elbv2 describe-load-balancers > lb-status.json
        json_data=$(cat lb-status.json)
        state_code=$(echo "$json_data" | jq -r '.LoadBalancers[0].State.Code')
        if [[ "$state_code" == "active" ]]; then
          echo "true" > is-active.txt
        else
          echo "Load balancer is not ready yet..."
        fi
    done
  displayName: 'Wait for Load Balancer Status'

- script: |
    kubectl get ingress -n argocd $(kubectl get ingress -n argocd | awk 'NR>1{print $1}') -o=jsonpath="{'http://'}{.status.loadBalancer.ingress[].hostname}{'\n'}" > argocd-access.txt
    echo "admin" >> argocd-access.txt
    echo $(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d) >> argocd-access.txt
  displayName: 'Save Access'

- task: PublishBuildArtifacts@1
  displayName: 'Export Access'
  inputs:
    PathtoPublish: 'argocd-access.txt'
    ArtifactName: 'Access'
    publishLocation: 'Container'

- script: kubectl create -n argocd -f $(Agent.BuildDirectory)/s/argo-cd/application.yaml
  displayName: 'Create ArgoCD Application'


